//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public System.DateTime event_start { get; set; }
        public System.DateTime event_end { get; set; }
        public int event_id { get; set; }
        public string description { get; set; }
        public string title { get; set; }
        public string UserNameEmail { get; set; }
        public string day { get; set; }
    }
}
