//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RV_Group()
        {
            this.RV_KeyWords = new HashSet<RV_KeyWords>();
            this.RV_MessageInGroup = new HashSet<RV_MessageInGroup>();
            this.RV_UserJoinGroup = new HashSet<RV_UserJoinGroup>();
            this.RV_GroupMessages = new HashSet<RV_GroupMessages>();
        }
    
        public int groupId { get; set; }
        public string groupName { get; set; }
        public string ImgPath { get; set; }
        public string groupDescription { get; set; }
        public string creatorEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_KeyWords> RV_KeyWords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_MessageInGroup> RV_MessageInGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_UserJoinGroup> RV_UserJoinGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_GroupMessages> RV_GroupMessages { get; set; }
    }
}
