//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_GroupMessages1
    {
        public int ID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string userEmail { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string image { get; set; }
    
        public virtual RV_User RV_User { get; set; }
    }
}
