//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_KNNCategory
    {
        public string email { get; set; }
        public Nullable<int> red { get; set; }
        public Nullable<int> white { get; set; }
        public Nullable<int> rose { get; set; }
        public Nullable<int> bubble { get; set; }
        public Nullable<int> Galil { get; set; }
        public Nullable<int> Golan { get; set; }
        public Nullable<int> Carmel { get; set; }
        public Nullable<int> negev { get; set; }
        public Nullable<int> shomron { get; set; }
        public Nullable<int> yehuda { get; set; }
    }
}
