//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_KeyWords
    {
        public int keyWordNum { get; set; }
        public string keyWord { get; set; }
        public Nullable<int> groupId { get; set; }
    
        public virtual RV_Group RV_Group { get; set; }
    }
}
