//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_LikesUsers
    {
        public int ID { get; set; }
        public Nullable<int> entityType { get; set; }
        public Nullable<int> entityId { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual RV_EntityTypes RV_EntityTypes { get; set; }
        public virtual RV_User RV_User { get; set; }
    }
}
