//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_MessageInGroup
    {
        public int messageId { get; set; }
        public Nullable<System.DateTime> sentTime { get; set; }
        public Nullable<System.DateTime> sentDate { get; set; }
        public string content { get; set; }
        public Nullable<int> groupId { get; set; }
        public string senderEmail { get; set; }
    
        public virtual RV_Group RV_Group { get; set; }
    }
}
