//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_PurchasedEventsByUsers
    {
        public int purchaseId { get; set; }
        public int ticketsPurchased { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public Nullable<System.DateTime> purchaseTime { get; set; }
        public Nullable<int> eventId { get; set; }
        public string email { get; set; }
        public byte[] rowVersion { get; set; }
    
        public virtual RV_Event RV_Event { get; set; }
    }
}
