//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RV_User()
        {
            this.RV_GroupMessages = new HashSet<RV_GroupMessages>();
            this.RV_GroupMessages1 = new HashSet<RV_GroupMessages1>();
            this.RV_UserPrefrences = new HashSet<RV_UserPrefrences>();
            this.RV_Winery = new HashSet<RV_Winery>();
            this.RV_Rate = new HashSet<RV_Rate>();
            this.RV_LikesUsers = new HashSet<RV_LikesUsers>();
            this.RV_WineComment = new HashSet<RV_WineComment>();
        }
    
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> typeId { get; set; }
        public string Name { get; set; }
        public string picture { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
        public Nullable<bool> isOlder { get; set; }
        public string token { get; set; }
        public Nullable<bool> isPremium { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_GroupMessages> RV_GroupMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_GroupMessages1> RV_GroupMessages1 { get; set; }
        public virtual RV_UserType RV_UserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_UserPrefrences> RV_UserPrefrences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_Winery> RV_Winery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_Rate> RV_Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_LikesUsers> RV_LikesUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_WineComment> RV_WineComment { get; set; }
    }
}
