//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_Winery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RV_Winery()
        {
            this.RV_Wine = new HashSet<RV_Wine>();
            this.RV_WineryCommand = new HashSet<RV_WineryCommand>();
            this.RV_Service = new HashSet<RV_Service>();
        }
    
        public int wineryId { get; set; }
        public string wineryName { get; set; }
        public string wineryAddress { get; set; }
        public string wineryEmail { get; set; }
        public string phone { get; set; }
        public string statusType { get; set; }
        public string IconImgPath { get; set; }
        public Nullable<int> areaId { get; set; }
        public string wineryManagerEmail { get; set; }
    
        public virtual RV_User RV_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_Wine> RV_Wine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_WineryCommand> RV_WineryCommand { get; set; }
        public virtual RV_AreaCategory RV_AreaCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_Service> RV_Service { get; set; }
    }
}
