//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareCours
    {
        public int Id { get; set; }
        public string ShareTo { get; set; }
        public string ShareFromUserName { get; set; }
        public string HTML { get; set; }
        public string CourseName { get; set; }
    }
}
