//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string UserNameEmail { get; set; }
        public string Password { get; set; }
        public string ProfilePic { get; set; }
    }
}
