//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winery
    {
        public int ID { get; set; }
        public string WineryName { get; set; }
        public string WineryImage { get; set; }
        public Nullable<int> CatgeoryID { get; set; }
    }
}
