// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace APIML.Model
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("text"), LoadColumn(1)]
        public string Text { get; set; }


        [ColumnName("date"), LoadColumn(2)]
        public string Date { get; set; }


        [ColumnName("email"), LoadColumn(3)]
        public string Email { get; set; }


        [ColumnName("wineId"), LoadColumn(4)]
        public float WineId { get; set; }


        [ColumnName("type"), LoadColumn(5)]
        public string Type { get; set; }


    }
}
